import { Platform, Pressable, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Avatar } from '@/components/Avatar';
import { Screen } from '@/components/Screen';
import { WebPeople } from '@/components/WebSections';
import { useApp } from '@/context/AppContext';
import { colors } from '@/theme/colors';
export default function PeopleScreen() { const { width } = useWindowDimensions(); const { chats } = useApp(); if (Platform.OS === 'web' && width >= 820) return <WebPeople />; return <Screen><View style={styles.header}><Text style={styles.title}>People</Text><Pressable onPress={() => router.push('/new-chat')} style={styles.new}><Ionicons name="person-add" size={21} color={colors.navy950} /></Pressable></View><Text style={styles.caption}>Contacts exist by Macro ID—your address book stays private.</Text><View style={styles.quick}><Ionicons name="qr-code" size={27} color={colors.neon} /><View><Text style={styles.name}>Share your QR code</Text><Text style={styles.meta}>Let trusted people connect instantly</Text></View></View><Text style={styles.section}>{chats.length} CONNECTIONS</Text>{chats.filter((chat) => !chat.isGroup).map((chat) => <Pressable key={chat.id} style={styles.row} onPress={() => router.push({ pathname: '/chat/[id]', params: { id: chat.id } })}><Avatar name={chat.name} color={chat.avatarColor} online={chat.online} imageUrl={chat.avatarUrl} /><View style={{ flex: 1 }}><Text style={styles.name}>{chat.name}</Text><Text style={styles.meta}>{chat.macroId}</Text></View><Ionicons name="chatbubble-outline" color={colors.blue} size={21} /></Pressable>)}</Screen>; }
const styles = StyleSheet.create({ header: { padding: 20, paddingTop: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { color: colors.white, fontSize: 32, fontWeight: '900' }, new: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.blue, alignItems: 'center', justifyContent: 'center' }, caption: { color: colors.muted, paddingHorizontal: 20, lineHeight: 20 }, quick: { margin: 20, padding: 16, borderRadius: 18, backgroundColor: colors.navy800, flexDirection: 'row', alignItems: 'center', gap: 14 }, section: { color: colors.blue, marginHorizontal: 20, marginBottom: 8, fontSize: 11, letterSpacing: 1.4, fontWeight: '900' }, row: { paddingHorizontal: 20, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 14 }, name: { color: colors.white, fontWeight: '800', fontSize: 15 }, meta: { color: colors.muted, fontSize: 12, marginTop: 4 } });
